### PR TITLE
Change AppStream ID to a reverse-DNS identifier

### PR DESCRIPTION
**Pull request by musicinmybrain**
Changes the AppStream ID to a reverse-DNS identifier per the [FreeDesktop specification](https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-id-generic). AppStream XML and `.desktop` files are renamed according to the new ID. I chose `io.github.qalculate.qt`, but this could be something else unique. If there is a domain controlled by the developers, that would probably be even better than using `github.io`. 

Uses the modern `.metainfo.xml` extension instead of the [historical but still acceptable](https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#spec-component-location) `.appdata.xml`.

### CODE REVIEW

**Comment by musicinmybrain** [comment]
```
$ appstreamcli validate --nonet data/io.github.qalculate.qt.metainfo.xml
I: io.github.qalculate.qt:60: nonstandard-gnome-extension kudos

Validation was successful: infos: 1
```

**Comment by hanna-kn** [comment]
> I chose io.github.qalculate.qt, but this could be something else unique.

The Flatpak package uses io.github.Qalculate.qalculate-qt.

**Comment by musicinmybrain** [comment]
> The Flatpak package uses io.github.Qalculate.qalculate-qt.

Thanks! I’ll adjust this PR to use that instead.

**Comment by musicinmybrain** [comment]
```
$ appstreamcli validate --nonet data/io.github.Qalculate.qalculate-qt.metainfo.xml 
I: io.github.Qalculate.qalculate-qt:3: cid-contains-hyphen io.github.Qalculate.qalculate-qt
I: io.github.Qalculate.qalculate-qt:60: nonstandard-gnome-extension kudos

Validation was successful: infos: 2, pedantic: 1
```

**Comment by musicinmybrain** [comment]
Thanks!

**Pull request merged**
